services:
  - type: web
    runtime: docker
    name: jeopardAi-app
    region: frankfurt
    plan: free
    healthCheckPath: /up
    autoDeploy: false
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: jeopardAi-redis
          property: connectionString
      - fromGroup: jeopardAi-envs
  - type: redis
    name: jeopardAi-redis
    ipAllowList: []
    plan: free
    region: frankfurt

envVarGroups:
  - name: jeopardAi-envs
    envVars:
      - key: REDIS_CONNECTION_POOL_SIZE
        value: "45"
      - key: OPEN_AI_IMAGE_GENERATOR_URL
        value: "https://api.openai.com/v1/images/generations"
      - key: OPEN_AI_IMAGE_MODEL
        value: "dall-e-3"
      - key: OPEN_AI_IMAGE_DEFAULT_SIZE
        value: "1024x1024"
      - key: OPEN_AI_TEXT_GENERATOR_URL
        value: "https://api.openai.com/v1/chat/completions"
      - key: OPEN_AI_TEXT_MODEL
        value: "gpt-3.5-turbo"
      - key: OPEN_AI_TEXT_MODEL
        value: "gpt-3.5-turbo"
