:concurrency: 3
:timeout: 60
:verbose: true
:queues:
  - default
:scheduler:
  :schedule:
    DailyGenerationJob:
      every: ['24h', first_in: '3s']
      enabled: true
      queue: default
      description: "Generate daily Open AI image jeopardy"
